name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy na Hostinger
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9]
    environment: deploy
    steps:
      - name: Verifica se ocorreu commits recentes
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Instala o pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Gerencia versão do NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Instala as dependências
      - run: pnpm install --no-frozen-lockfile
      - name: Inicia Build do projeto
        run: pnpm run build
      - name: Sincroniza com o servidor
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: ./dist/
          server-dir: public_html/
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
